# Generated by Django 4.0.5 on 2022-06-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_location_user_location_id_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location_id',
            field=models.ManyToManyField(blank=True, related_name='locations', to='users.location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
