# Generated by Django 4.0.5 on 2022-06-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_category_alter_ad_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('true', 'опубликовано'), ('false', 'не опубликовано')], default='false', max_length=5),
        ),
    ]
