# Generated by Django 4.0.5 on 2022-06-15 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('ads', '0004_ad_image_ad_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.CharField(max_length=30),
        ),
    ]
