# Generated by Django 4.0.5 on 2022-06-15 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('ads', '0005_ad_author_id_alter_ad_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='author_id',
        ),
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
