# Generated by Django 4.0.5 on 2022-06-17 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_location_id_user_locations'),
        ('ads', '0009_rename_author_id_ad_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='created',
        ),
        migrations.AddField(
            model_name='ad',
            name='author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='ad',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.category'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.CharField(default='anonim', max_length=30),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
