# Generated by Django 4.0.5 on 2022-06-19 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_location_id_user_locations'),
        ('ads', '0010_remove_ad_created_ad_author_id_ad_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='category_id',
        ),
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.category'),
        ),
    ]
